### ISSUE TITLE
Convert to newer version of Unity

### ISSUE THREAD

**Issue by donaldmurf** [donaldmurf/VFV#14]
please create branch and link it to this issue.

**Comment by Aseklawi** [comment]
Hey dom.
 I talked to Mohsen and he sent you a massage but I’m with the omega time and you assigned issue #8 and #14 for me. I’m checking the mindmap and I see where taht mistaken might of happened. I’m sure you were supposed to assign that to Alex. Lol it happens. Just letting you know so there is no issues with you and your group in the future. 

Also I need to fill out the data model and description of the game for my class. I was wondering if you could help me with that. This is my what’s app number 3136453305 and we can communicate on there if it’s easier!!

>

**Comment by donaldmurf** [comment]
![image](https://user-images.githubusercontent.com/79768202/199984450-58165a38-ce0d-4a79-98a8-b636687201a2.png)

**Comment by donaldmurf** [comment]
![image](https://user-images.githubusercontent.com/79768202/199985136-ad8b3096-d0be-4425-9b7c-18fa4505e7ce.png)

**Comment by donaldmurf** [comment]
unityhub://2022.1.20f1/01d83b40d570

**Comment by donaldmurf** [comment]
![image](https://user-images.githubusercontent.com/79768202/199988545-bbc5ab7c-8a89-472d-89e9-460caf690dc4.png)

**Comment by donaldmurf** [comment]
Game runs, check out a few things and found no issues.
