### ISSUE TITLE
Publish game

### ISSUE THREAD

**Issue by donaldmurf** [donaldmurf/VFV#17]
Make a branch of the game from its executable state and publish a release for it. There is another issue associated with this, which is making a video on how to get the game running on the end users side.

**Comment by donaldmurf** [comment]
I believe this issue is done. @mohsenc or @dkibrahi, would you mind closing this? Thanks.

**Comment by dkibrahi** [comment]
Email sent to counselors. Waiting for a response from one of the counselors. Need to follow up and get their feedback
