### ISSUE TITLE
Bookstore Content

### ISSUE THREAD

**Issue by mohsenc** [donaldmurf/VFV#27]
Award points for books bought and read in selected assessment points

**Comment by mohsenc** [comment]
I found that the messages for books work differently than the messages for NPC's as in #INCREASE#*Crit* will increase critical skill with NPC but not with book
In order to solve this, we added functionality to book_item.cs 
Book attribute "Details" is used to store the name of the skill to be updated!

**Comment by donaldmurf** [comment]
![image](https://user-images.githubusercontent.com/79768202/198702613-27360070-ba95-4e8a-a366-2ded44a98983.png)
![image](https://user-images.githubusercontent.com/79768202/198703503-c5fdac6d-24cb-4c19-8ea9-caae3ba2de5b.png)
![image](https://user-images.githubusercontent.com/79768202/198703649-5d6cf00c-eb76-4deb-b404-07d1036df6d7.png)
![image](https://user-images.githubusercontent.com/79768202/198703944-34b832d4-372e-40c9-8fab-25fded13f48d.png)

**Comment by donaldmurf** [comment]
If you notice NPCs use Messages from TalkToNPCs.cs and Books use Use_Dialogue.
![image](https://user-images.githubusercontent.com/79768202/198704246-e395be6a-680c-41e5-8a7c-3099b18e7b3d.png)

**Comment by donaldmurf** [comment]
Currently I'm thinking we need to do an if statement for "messages" in TalkToNPC.cs.

Basically, the current messages looks at NPC messages. We want to add the logic,  if(item is used){messages = Use_Dialogue}.

**Comment by donaldmurf** [comment]
![image](https://user-images.githubusercontent.com/79768202/201417919-d029c296-5929-4808-89c0-3056354f1ad8.png)
![image](https://user-images.githubusercontent.com/79768202/201418199-1fdc81a4-5ed9-4467-9695-fce08eabc219.png)
![image](https://user-images.githubusercontent.com/79768202/201418845-8b4ec2f7-8158-462d-b7f8-0088f0debec8.png)
![image](https://user-images.githubusercontent.com/79768202/201419097-05fec452-9c04-4d1b-a4c9-90d7a81077d6.png)
![image](https://user-images.githubusercontent.com/79768202/201419889-19c9f92c-4cd0-4d32-9f0c-f61fb792884f.png)

**Comment by donaldmurf** [comment]
Inventory_Item has bookStats
BookStore has Use_Dialogue array
Use_Dialogue arry has book (which inherets bookStats from Inventory_Item)

BooksStoreItems have attributes. The one we care about is bookStoreStats

bookStoreStats is 7th parameter for all of the Books. 

To update stats of a book: go to the BS_Items array and add a string that works with ReplaceKeyWords.
Example: The brainteasers 7th arguement is "#INCREASE#*Crit* +1 to critical thinking!"
This will add one to critical thinking stat along with message "+1 to critical thinking!"

I will add comments in that area to reference adding any stat.

**Comment by donaldmurf** [comment]
![1No books read](https://user-images.githubusercontent.com/79768202/204025743-a5aacdf6-5950-4910-8f1e-23e998d66262.png)
![2What to say and how to say it](https://user-images.githubusercontent.com/79768202/204025746-eaa31bf9-20e9-4d59-824a-4784fa5be255.png)
![3Brain Teasers](https://user-images.githubusercontent.com/79768202/204025751-95fbc66e-b5ef-44d6-8829-b0b6c09bf3c3.png)
![4team synergy](https://user-images.githubusercontent.com/79768202/204025758-2c42dc20-de9a-456d-892e-7c9006d531b1.png)
![5hiring manager](https://user-images.githubusercontent.com/79768202/204025760-ee23d086-68f2-4f65-9e01-e6df90ab1357.png)
![6principals of man](https://user-images.githubusercontent.com/79768202/204025659-152e24b5-b328-44b2-8962-beb05a56ee25.png)
![7employment laws](https://user-images.githubusercontent.com/79768202/204025666-b993bde8-ac3c-43a8-b8f5-4f8693cd816f.png)
![8compTia](https://user-images.githubusercontent.com/79768202/204025672-d520186f-2559-4b3c-aae2-5a20dd9cb4c4.png)
![9intro hardware](https://user-images.githubusercontent.com/79768202/204025673-8672d4ec-d288-438c-a7bf-6fb4dc7606f5.png)
![10troubleshooting](https://user-images.githubusercontent.com/79768202/204025681-aa0792fb-1322-4e3b-a858-88d5eaed1d36.png)
![11guide networking](https://user-images.githubusercontent.com/79768202/204025686-5907f2c9-33bb-486b-ac3a-4cab682de09d.png)
![12how better leader](https://user-images.githubusercontent.com/79768202/204025689-a077f313-cf63-4720-b55e-2df1531636a7.png)
![13intro python](https://user-images.githubusercontent.com/79768202/204025691-f39a2a6f-18cb-4e96-8d51-0f5ee5c571b1.png)
![14software principals](https://user-images.githubusercontent.com/79768202/204025693-5241cb64-1482-4d35-b291-0b6cd88addd5.png)
![15debugging](https://user-images.githubusercontent.com/79768202/204025699-e7954413-af1f-4a46-b4f9-e70e5478e545.png)
![16game design](https://user-images.githubusercontent.com/79768202/204025701-0a23b4c3-baa8-4f7b-8ee4-92d17019514f.png)
![17working team](https://user-images.githubusercontent.com/79768202/204025705-7995a105-379a-469a-8eb0-16842ad8933a.png)
![18microswift](https://user-images.githubusercontent.com/79768202/204025710-74c4f16d-c3e4-4dca-ba31-7c6b66d68f44.png)
![19principals eng](https://user-images.githubusercontent.com/79768202/204025715-322cd16e-bc7f-4f0f-94b0-6eb5c7ad13a5.png)
![20i inc](https://user-images.githubusercontent.com/79768202/204025721-eab0019e-45a4-48eb-981c-1feed991c053.png)
![21already read book](https://user-images.githubusercontent.com/79768202/204025724-8de1053a-7b26-49db-a53a-f0eaa1684eb3.png)
![21tiger](https://user-images.githubusercontent.com/79768202/204025730-37f4caf2-491f-450b-9d49-363fa3e6933b.png)
![22BUG teamwork off by 2 points](https://user-images.githubusercontent.com/79768202/204025736-bb8703a7-eb76-45e2-afde-6a022f74775f.png)

**Comment by donaldmurf** [comment]
com=1
crit=2
team=2
lead=3
tech=8
prof=4
Total=20

**Comment by donaldmurf** [comment]
Fixed leadership bug. All books are tracked in player results file 
[Player 11-25-2022 H14M0S20.txt](https://github.com/donaldmurf/VFV/files/10094736/Player.11-25-2022.H14M0S20.txt)
and all stats are updated as they should be
![image](https://user-images.githubusercontent.com/79768202/204042789-b784a22c-690f-4c5c-9097-7f51755d6112.png)
![Uploading image.png…]()
