### ISSUE TITLE
Add Linkedin

### ISSUE THREAD

**Issue by dkibrahi** [donaldmurf/VFV#44]
finishing touches of add linkedin branch

**Comment by donaldmurf** [comment]
![image](https://user-images.githubusercontent.com/79768202/203655434-bf087b80-22b5-4c6c-b1a6-156edc1c4f03.png)

**Comment by donaldmurf** [comment]
![image](https://user-images.githubusercontent.com/79768202/203655588-b8eab78b-e1f0-4eb4-8709-d2bff36deef1.png)

**Comment by donaldmurf** [comment]
fixed that bug..
